name: licheckers
region: nyc

# Frontend service
services:
  - name: licheckers-client
    github:
      repo: kaarti19900105/licheckers
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: npm install --include=dev && cd client && npm run build
    run_command: cd client && npm run preview -- --host 0.0.0.0 --port 4173
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 4173
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: ${licheckers-server.PUBLIC_URL}
        scope: RUN_TIME

  # Backend service
  - name: licheckers-server
    github:
      repo: kaarti19900105/licheckers
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: npm install --include=dev && cd server && npm run build
    run_command: cd server && npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3001
    routes:
      - path: /api
      - path: /socket.io
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
        scope: RUN_TIME
      - key: CORS_ORIGIN
        value: ${licheckers-client.PUBLIC_URL}
        scope: RUN_TIME

# PostgreSQL database
databases:
  - name: db
    engine: PG
    version: "15"
    production: false
    cluster_name: licheckers-db
    db_name: licheckers
    db_user: licheckers
